In [4]:
# import pandas
import pandas as pd

In [3]:
# show rows and columns
df.shape

(3, 2)

In [7]:
!pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 3.0 MB/s  0:00:05m 3.0 MB/s eta 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.13/site-packages (from pydataset) (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /opt/miniconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.13/site-packages (from pandas->pydataset) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas->pydataset) (1.17.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (pyproject.toml) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939220 sha256=4bce828cbf85ddc298c4c2a7ac1f7f5d0cdc60a4d97f7853e797beb355aa499a
  Stored in directory: /Users/zoeysahibzada/Library/Caches/pip/wheels/49/2a/45/180e1199b8d925b5c43df8f9850dcc2e5dfc94e3e99a55b83e
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [8]:
# load dataset
from pydataset import data
mtcars = data('mtcars')

initiated datasets repo at: /Users/zoeysahibzada/.pydataset/

In [9]:
# show first rows
mtcars.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [10]:
# show shape
mtcars.shape

(32, 11)

In [11]:
# show columns
mtcars.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear',
       'carb'],
      dtype='str')

In [12]:
# show data types 
mtcars.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [13]:
# summary statistics
mtcars.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [14]:
# show last rows
mtcars.tail()

                 mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  carb
Lotus Europa    30.4    4   95.1  113  3.77  1.513  16.9   1   1     5     2
Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5     4
Ferrari Dino    19.7    6  145.0  175  3.62  2.770  15.5   0   1     5     6
Maserati Bora   15.0    8  301.0  335  3.54  3.570  14.6   0   1     5     8
Volvo 142E      21.4    4  121.0  109  4.11  2.780  18.6   1   1     4     2

In [15]:
# show random rows
mtcars.sample(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4

In [16]:
# count unique values
mtcars.nunique()

mpg     25
cyl      3
disp    27
hp      22
drat    22
wt      29
qsec    30
vs       2
am       2
gear     3
carb     6
dtype: int64

In [18]:
# missing values
mtcars.isnull().sum()

mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [19]:
# value count for cylinders
mtcars["cyl"].value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [20]:
# save to csv
mtcars.to_csv('mtcarsdata.csv',index=False)

In [21]:
# read csv file
mtcars2 =pd.read_csv('mtcarsdata.csv')

# show data
mtcars2.head()

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [24]:
mtcars.iloc[0]

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: Mazda RX4, dtype: float64

mtcars.iloc[3:5]

In [25]:
mtcars.iloc[0,4]

np.float64(3.9)

In [27]:
mtcars.head(5)

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [28]:
mtcars.loc['Datsun 710']

mpg      22.80
cyl       4.00
disp    108.00
hp       93.00
drat      3.85
wt        2.32
qsec     18.61
vs        1.00
am        1.00
gear      4.00
carb      1.00
Name: Datsun 710, dtype: float64