In [1]:
import pandas as pd

data = {
    "mpg":[21.0,21.0,22.8,21.4,18.7],
    "cyl":[6,6,4,6,8],
    "disp":[160,160,108,258,360],
    "hp":[110,110,93,110,175],
    "drat":[3.9,3.9,3.85,3.08,3.15],
    "wt":[2.62,2.875,2.32,3.215,3.44],
    "qsec":[16.46,17.02,18.61,19.44,17.02],
    "vs":[0,0,1,1,0],
    "am":[1,1,1,0,0],
    "gear":[4,4,4,3,3],
    "carb":[4,4,1,1,2]
}

mtcars = pd.DataFrame(data)
mtcars

    mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6   160  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6   160  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4   108   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6   258  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8   360  175  3.15  3.440  17.02   0   0     3     2

In [2]:
mtcars.head(2)

    mpg  cyl  disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6   160  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6   160  110   3.9  2.875  17.02   0   1     4     4

In [3]:
mtcars.dtypes

mpg     float64
cyl       int64
disp      int64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [4]:
mtcars = mtcars.astype({
    "cyl":"category",
    "vs":"category",
    "carb":"category",
    "am":"category"
})

In [5]:
mtcars.dtypes

mpg      float64
cyl     category
disp       int64
hp         int64
drat     float64
wt       float64
qsec     float64
vs      category
am      category
gear       int64
carb    category
dtype: object